service: happy-stars

custom:
  github-repo:
    Owner: timbaer
    Repo: happy-stars
    Branch: master
    OAuthToken: ${ssm:/aws/reference/secretsmanager/sls-github-token~true}

plugins:
  - serverless-stack-output

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: eu-west-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: ["arn:aws:s3:::*" ]
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "*"

  environment:
    STARS_DYNAMODB_ARN: { "Fn::GetAtt": ["starsTable", "Arn"] }
    UNIVERSES_DYNAMODB_ARN: { "Fn::GetAtt": ["universesTable", "Arn"] }

package:
  individually: true

functions:
  universes:
    environment:
      QUARKUS_LAMBDA_HANDLER : universes
    runtime: java11
    package:
      artifact: backend/target/happystars-runner.jar
    handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
    events:
      - http:
          path: universes
          method: get
      - http:
          path: universes/{id}
          method: get
          request:
            parameters:
              paths:
                id: false
      - http:
          path: universes/{id}
          method: delete
          request:
            parameters:
              paths:
                id: true
      - http:
          path: universes
          method: post
  stars:
    environment:
      QUARKUS_LAMBDA_HANDLER: stars
    runtime: java11
    package:
      artifact: backend/target/happystars-runner.jar
    handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
    events:
      - http:
          path: stars
          method: get
      - http:
          path: stars/{id}
          method: get
          request:
            parameters:
              paths:
                id: false
      - http:
          path: stars/{id}
          method: delete
          request:
            parameters:
              paths:
                id: true
      - http:
          path: stars
          method: post

resources:
  - ${file(./sls-and-infra/CICD.yml)}
  - Resources:
      universesTable:
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: universes-${opt:stage}
          AttributeDefinitions:
            - AttributeName: id
              AttributeType: N
            - AttributeName: name
              AttributeType: S
          KeySchema:
            - AttributeName: id
              KeyType: HASH
            - AttributeName: name
              KeyType: RANGE
          BillingMode: PAY_PER_REQUEST
      starsTable:
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: stars-${opt:stage}
          AttributeDefinitions:
            - AttributeName: id
              AttributeType: N
            - AttributeName: name
              AttributeType: S
          KeySchema:
            - AttributeName: id
              KeyType: HASH
            - AttributeName: name
              KeyType: RANGE
          BillingMode: PAY_PER_REQUEST
