service: happy-stars

custom:
  github-repo:
    Owner: timbaer
    Repo: happy-stars
    Branch: master
    OAuthToken: ${ssm:/aws/reference/secretsmanager/sls-github-token~true}

plugins:
  - serverless-stack-output

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: eu-west-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: ["arn:aws:s3:::*" ]

  environment:
      variable1: value1

package:
  individually: true

functions:
  universes:
    runtime: java11
    package:
      artifact: backend/target/happystars-universes-runner.jar
    handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
    events:
      - http:
          path: universes
          method: get
      - http:
          path: universes/{id}
          method: get
          request:
            parameters:
              paths:
                id: false
      - http:
          path: universes/{id}
          method: delete
          request:
            parameters:
              paths:
                id: true
      - http:
          path: universes
          method: post
  stars:
    runtime: java11
    package:
      artifact: backend/target/happystars-stars-runner.jar
    handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
    events:
      - http:
          path: stars
          method: get
      - http:
          path: stars/{id}
          method: get
          request:
            parameters:
              paths:
                id: false
      - http:
          path: stars/{id}
          method: delete
          request:
            parameters:
              paths:
                id: true
      - http:
          path: stars
          method: post
resources:
  - ${file(./sls-and-infra/CICD.yml)}
  - Resources:
      universesTable:
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: happStarsUniverses-${opt:stage}
          AttributeDefinitions:
            - AttributeName: id
              AttributeType: S
          KeySchema:
            - AttributeName: id
              KeyType: HASH
          BillingMode: PAY_PER_REQUEST

