version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
  pre_build:
    commands:
  build:
    commands:
      # maven build - backend
      - cd $CODEBUILD_SRC_DIR/backend
      - mvn clean install --no-transfer-progress
      - mvn install --no-transfer-progress -Dquarkus.lambda.handler=stars

      - cd $CODEBUILD_SRC_DIR
      # prepare a deployment ready app for the prod stage
      - serverless package --stage prod --package package
      # pack and deploy a staging stage
      - serverless deploy --stage staging
artifacts:
      files:
        - sls-and-infra/**/*
        - serverless.yml
        - package.json
        - backend/target/**/*
        - package/**/*
