version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
      nodejs: 10
  pre_build:
    commands:
      - npm install
      - PATH=$(npm bin):$PATH
  build:
    commands:
      # maven build - backend
      - cd $CODEBUILD_SRC_DIR
      - ./mvnw -f backend clean install
      - ./mvnw -f backend install -Dquarkus.lambda.handler=stars

      - cd $CODEBUILD_SRC_DIR
      # prepare a deployment ready app for the prod stage
      - serverless package --stage prod --package package
      # pack and deploy a staging stage
      - serverless deploy --stage staging
artifacts:
      files:
        - sls-and-infra/**/*
        - serverless.yml
        - package.json
        - backend/target/**/*
        - package/**/*
